<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'No draft exists with the Id “{entryId}”.' => '',
  'No entry exists with the Id “{entryId}”.' => '',
  'No section exists with the Id “{sectionId}”' => '',
  'The content row can’t be inserted into the database because it’s not new.' => '',
  'The content row can’t be inserted into the database before it’s record has been saved.' => '',
  'The content row can’t be updated because it’s new.' => '',
);
