<?php

namespace CraftCms\Cms\Database\Migrations;

use CraftCms\Cms\Database\Migration;
use CraftCms\Cms\Database\Table;
use CraftCms\Cms\Element\Models\EntryType;
use CraftCms\Cms\Section\Enums\SectionType;
use CraftCms\Cms\Support\Arr;
use CraftCms\Cms\Support\Json;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Facades\DB;
use Tpetry\QueryExpressions\Language\Alias;

use function Laravel\Prompts\progress;

/**
 * Base entry type merge migration class.
 *
 * This is extended by content migrations generated by the `entry-types/merge` command.
 *
 * @since 5.3.0
 */
class BaseEntryTypeMergeMigration extends Migration
{
    public string $persistingEntryTypeUid;

    public string $outgoingEntryTypeUid;

    /** @var array<string,string> */
    public array $layoutElementUidMap;

    public function up(): void
    {
        $this->newLine();

        /** @var EntryType|null $persistingEntryTypeRecord */
        $persistingEntryTypeRecord = EntryType::withTrashed()
            ->where('uid', $this->persistingEntryTypeUid)
            ->firstOrFail();

        /** @var EntryType|null $outgoingEntryTypeRecord */
        $outgoingEntryTypeRecord = EntryType::withTrashed()
            ->where('uid', $this->outgoingEntryTypeUid)
            ->firstOrFail();

        $query = DB::table(Table::ELEMENTS_SITES, 'es')
            ->select(['es.id', 'es.content'])
            ->join(new Alias(Table::ENTRIES, 'e'), 'e.id', '=', 'es.elementId')
            ->where('e.typeId', $outgoingEntryTypeRecord->id)
            ->whereNotNull('es.content');

        $this->updateContentAndRestore($query, $outgoingEntryTypeRecord);

        // and now special case for singles
        $query = DB::table(Table::ELEMENTS_SITES, 'es')
            ->select(['es.id', 'es.content'])
            ->join(new Alias(Table::ENTRIES, 'e'), 'e.id', '=', 'es.elementId')
            ->leftJoin(new Alias(Table::SECTIONS, 's'), 'e.sectionId', '=', 's.id')
            ->whereNotNull('es.content')
            ->where('s.type', SectionType::Single->value);

        if ($query->count() > 0) {
            $this->info('Updating singles');
            $this->updateContentAndRestore($query, $persistingEntryTypeRecord);
        }

        $this->components->task('Reassigning entries', function () use ($persistingEntryTypeRecord, $outgoingEntryTypeRecord) {
            DB::table(Table::ENTRIES)
                ->where('typeId', $outgoingEntryTypeRecord->id)
                ->update([
                    'typeId' => $persistingEntryTypeRecord->id,
                    'deletedWithEntryType' => false,
                    'dateUpdated' => now(),
                ]);
        });
    }

    private function updateContentAndRestore(
        Builder $query,
        EntryType $entryTypeRecord,
    ): void {
        if ($total = $query->count()) {
            $progress = progress('Updating content', $total);

            $query->lazyById(column: 'es.id')
                ->each(function (object $row) use ($progress) {
                    $progress->hint(Table::ELEMENTS_SITES."#{$row->id}");
                    $progress->render();

                    $content = Json::decode($row->content);
                    $changed = false;
                    foreach ($this->layoutElementUidMap as $oldUid => $newUid) {
                        if (array_key_exists($oldUid, $content)) {
                            $content[$newUid] = Arr::pull($content, $oldUid);
                            $changed = true;
                        }
                    }

                    if ($changed) {
                        DB::table(Table::ELEMENTS_SITES)
                            ->where('id', $row->id)
                            ->update([
                                'content' => $content,
                                'dateUpdated' => now(),
                            ]);
                    }

                    $progress->advance();
                });

            $progress->finish();
        } else {
            $this->components->task('Updating content');
        }

        $this->components->task('Restoring entries', function () use ($entryTypeRecord) {
            DB::table(Table::ELEMENTS, 'elements')
                ->join(new Alias(Table::ENTRIES, 'entries'), 'entries.id', '=', 'elements.id')
                ->where('entries.typeId', $entryTypeRecord->id)
                ->where('entries.deletedWithEntryType', true)
                ->update([
                    'elements.dateDeleted' => null,
                ]);
        });
    }
}
