<?php

declare(strict_types=1);

namespace CraftCms\Cms\Database\Migrations;

use CraftCms\Cms\Database\Migration;
use CraftCms\Cms\Field\Contracts\FieldInterface;
use CraftCms\Cms\Field\Contracts\MergeableFieldInterface;
use CraftCms\Cms\Field\MissingField;
use CraftCms\Cms\Field\Models\Field;
use CraftCms\Cms\Support\Facades\Fields;
use RuntimeException;

/**
 * Base field merge migration class.
 *
 * This is extended by content migrations generated by the `fields/merge` command.
 *
 * @since 5.3.0
 */
class BaseFieldMergeMigration extends Migration
{
    public string $persistingFieldUid;

    public string $outgoingFieldUid;

    public function up(): void
    {
        /** @var MergeableFieldInterface|false $persistingField */
        $persistingField = $this->field($this->persistingFieldUid);
        if (! $persistingField) {
            throw new RuntimeException;
        }

        /** @var MergeableFieldInterface|false $outgoingField */
        $outgoingField = $this->field($this->outgoingFieldUid);
        if (! $outgoingField) {
            throw new RuntimeException;
        }

        $reason = null;
        if (! $outgoingField->canMergeInto($persistingField, $reason)) {
            $this->error(sprintf(
                "%s (%s) doesn’t support merging into %s (%s)%s\n",
                $outgoingField->name,
                $outgoingField::displayName(),
                $persistingField->name,
                $persistingField::displayName(),
                $reason ? ": $reason" : '.',
            ));

            throw new RuntimeException;
        }

        $reason = null;
        if (! $persistingField->canMergeFrom($outgoingField, $reason)) {
            $this->error(sprintf(
                "%s (%s) doesn’t support being merged into from %s (%s)%s\n",
                $persistingField->name,
                $persistingField::displayName(),
                $outgoingField->name,
                $outgoingField::displayName(),
                $reason ? ": $reason" : '.',
            ));

            throw new RuntimeException;
        }

        $outgoingField->afterMergeInto($persistingField);
        $persistingField->afterMergeFrom($outgoingField);
    }

    private function field(string $uid): FieldInterface|false
    {
        $field = Fields::getFieldByUid($uid);

        if (! $field) {
            // maybe it's soft-deleted
            $record = Field::withTrashed()
                ->where('uid', $uid)
                ->firstOrFail();

            $field = Fields::createField($record->toArray());
        }

        if ($field instanceof MissingField) {
            $this->error("$field->expectedType is missing.");

            return false;
        }

        if (! $field instanceof MergeableFieldInterface) {
            $this->error("$field->name doesn’t support merging.");

            return false;
        }

        return $field;
    }
}
