codecov:
  require_ci_to_pass: yes
coverage:
  range: '20...100'
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: .1
  notify:
    slack:
      default:
        url: 'secret:M/dQaxt1nCzNG8JinXO5SmKdYoqErol7pzCV4Xv194cltAc0qu9WEezFP8Gnwkdg4eXfdxw2M0SbjcE8R8QB2B9n/YUHdXPdWsnhxa/HuIwc4kbvcaHyM7fU/lh7eWgYs4O5K3z/YnrirkmqNlzcgUuRmBOajf6MocPp4zd3sz8='
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment: off
github_checks:
  annotations: false
ignore:
  - 'bootstrap'
  - 'lib'
  - 'src/config'
  - 'src/icons'
  - 'src/migrations'
  - 'src/templates'
  - 'src/test/internal'
  - 'src/translations'
  - 'src/views'
  - 'src/web/assets'
  - 'tests'
  - 'vendor'
