codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "20...100"

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: 3.2
        flags: null
        attachments: "sunburst, diff"
        paths: null
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: off

ignore:
  - "src/web/assets"  # ignore assets folder
  - "src/test/internal" # ignore internal test material (I.E. the example test suite.)
