name: craft-source
recipe: lamp
services:
  appserver:
    type: php:7.3
    via: cli
    xdebug: true
    build:
      - composer update
    overrides:
      environment:
        # So xDebug will work from the command line
        PHP_IDE_CONFIG: "serverName=craft-source.lndo.site"
  database:
    type: mysql
    portforward: true