#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

// Project root path
$root = __DIR__;

// Composer autoloader
require_once $root.'/vendor/autoload.php';

// dotenv?
if (file_exists($root.'/.env')) {
    $dotenv = new Dotenv\Dotenv($root);
    $dotenv->load();
}

// Craft
define('CRAFT_BASE_PATH', $root);
define('CRAFT_ENVIRONMENT', getenv('CRAFT_ENVIRONMENT') ?: 'production');
$app = require $root.'/vendor/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
