project_identifier: craft-cms
api_key_env: CROWDIN_API_KEY
base_path: /src/translations
preserve_hierarchy: true
export_only_approved: true
files:
  - source: /en/app.php
    translation: /%two_letters_code%/app.php
    type: php
    excluded_target_languages:
      - cy
      - el
      - hr
      - id
      - ky
commit_message: '[ci skip]'
