version: '3.1'
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword1!
      MYSQL_DATABASE: craft-test
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_ROOT_PASSWORD: SuperPassword123456!
      POSTGRES_DB: craft-test
      POSTGRES_USER: craft
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  mysql_data:
  postgres_data:
