APP_ID=CraftCMS
CRAFT_SECURITY_KEY=UPzGqJJMCTM4n07jkqaFNaVoof6j_Xfo

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=craft_test
DB_USERNAME=root
DB_PASSWORD=
DB_SCHEMA=public

FROM_EMAIL_NAME="Craft CMS"
FROM_EMAIL_ADDRESS=info@craftcms.com

AUTH_MODEL=\CraftCms\Cms\User\Models\User
