<?php

declare(strict_types=1);

namespace CraftCms\Cms\FieldLayout\LayoutElements\users;

use craft\base\ElementInterface;
use CraftCms\Cms\Cms;
use CraftCms\Cms\FieldLayout\LayoutElements\TextField;
use CraftCms\Cms\Support\Arr;
use CraftCms\Cms\User\Elements\User;
use InvalidArgumentException;
use Override;

use function CraftCms\Cms\t;

class UsernameField extends TextField
{
    /**
     * {@inheritdoc}
     */
    public bool $mandatory = true;

    /**
     * {@inheritdoc}
     */
    public string $attribute = 'username';

    /**
     * {@inheritdoc}
     */
    public ?int $maxlength = 255;

    /**
     * {@inheritdoc}
     */
    public bool $autofocus = true;

    /**
     * {@inheritdoc}
     */
    public function __construct($config = [])
    {
        // We didn't start removing autofocus from fields() until 3.5.6
        parent::__construct(Arr::except($config, [
            'mandatory',
            'attribute',
            'translatable',
            'maxlength',
            'required',
            'autofocus',
        ]));
    }

    /**
     * {@inheritdoc}
     */
    #[Override]
    public function fields(): array
    {
        return Arr::except(parent::fields(), [
            'mandatory',
            'attribute',
            'translatable',
            'maxlength',
            'required',
            'autofocus',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function defaultLabel(?ElementInterface $element = null, bool $static = false): ?string
    {
        return t('Username');
    }

    #[Override]
    protected function inputHtml(?ElementInterface $element = null, bool $static = false): ?string
    {
        if (Cms::config()->useEmailAsUsername) {
            return null;
        }

        return parent::inputHtml($element, $static); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    #[Override]
    protected function inputAttributes(?ElementInterface $element = null, bool $static = false): array
    {
        if (! $element instanceof User) {
            throw new InvalidArgumentException(sprintf('%s can only be used in user field layouts.', self::class));
        }

        return [
            'autocomplete' => $element->getIsCurrent() ? 'username' : 'off',
        ];
    }
}
