APP_ID=CraftCMS
SECURITY_KEY=UPzGqJJMCTM4n07jkqaFNaVoof6j_Xfo

DB_DRIVER=pgsql
DB_SERVER=127.0.0.1
DB_PORT=5432
DB_DATABASE=craft_test
DB_USER=root
DB_PASSWORD=
DB_SCHEMA=public

FROM_EMAIL_NAME="Craft CMS"
FROM_EMAIL_ADDRESS=info@craftcms.com
