<?php
/**
 * @link https://craftcms.com/
 * @copyright Copyright (c) Pixel & Tonic, Inc.
 * @license https://craftcms.github.io/license/
 */

namespace craft\services;

use Craft;
use CraftCms\Cms\Cms;
use CraftCms\Cms\Support\Security as ModernSecurity;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;
use InvalidArgumentException;
use SensitiveParameter;
use yii\base\Exception;
use yii\base\InvalidConfigException;

/**
 * Security service.
 *
 * An instance of the service is available via [[\yii\base\Application::getSecurity()|`Craft::$app->getSecurity()`]].
 *
 * @author Pixel & Tonic, Inc. <support@pixelandtonic.com>
 * @since 3.0.0
 * @deprecated 6.0.0 use {@see \CraftCms\Cms\Support\Security} instead.
 */
class Security extends \yii\base\Security
{
    /**
     * @var string[] Keywords used to reference sensitive data.
     */
    public array $sensitiveKeywords = [
        'key',
        'pass',
        'password',
        'pw',
        'secret',
        'sk',
        'tok',
        'token',
    ];

    /**
     * @return int
     * @deprecated 6.0.0 use {@see Password} validation rules instead.
     */
    public function getMinimumPasswordLength(): int
    {
        $defaultRules = Password::default();

        return $defaultRules->appliedRules()['min'];
    }

    /**
     * Hashes a given password with the bcrypt blowfish encryption algorithm.
     *
     * @param string $password The string to hash
     * @param bool $validateHash If you want to validate the just generated hash. Will throw an exception if
     * validation fails.
     * @return string The hash.
     * @deprecated 6.0.0 use {@see Hash::make()} instead.
     */
    public function hashPassword(#[SensitiveParameter] string $password, bool $validateHash = false): string
    {
        $hash = Hash::make($password);

        if ($validateHash && !Hash::check($password, $hash)) {
            throw new InvalidArgumentException('Could not hash the given string.');
        }

        return $hash;
    }

    /**
     * @inheritdoc
     * @param string $data the data to be protected
     * @param string|null $key the secret key to be used for generating hash. Should be a secure
     * cryptographic key.
     * @param bool $rawHash whether the generated hash value is in raw binary format. If false, lowercase
     * hex digits will be generated.
     * @return string the data prefixed with the keyed hash
     * @throws Exception if the validation key could not be written
     * @throws InvalidConfigException when HMAC generation fails.
     * @deprecated 6.0.0 use {@see \CraftCms\Cms\Support\Security::hashData()} instead.
     */
    public function hashData(#[SensitiveParameter] $data, #[SensitiveParameter] $key = null, $rawHash = false): string
    {
        return Crypt::encrypt($data);
    }

    /**
     * @inheritdoc
     * @param string $data the data to be validated. The data must be previously
     * generated by [[hashData()]].
     * @param string|null $key the secret key that was previously used to generate the hash for the data in [[hashData()]].
     * function to see the supported hashing algorithms on your system. This must be the same
     * as the value passed to [[hashData()]] when generating the hash for the data.
     * @param bool $rawHash this should take the same value as when you generate the data using [[hashData()]].
     * It indicates whether the hash value in the data is in binary format. If false, it means the hash value consists
     * of lowercase hex digits only.
     * hex digits will be generated.
     * @return string|false the real data with the hash stripped off. False if the data is tampered.
     * @throws Exception if the validation key could not be written
     * @throws InvalidConfigException when HMAC generation fails.
     * @deprecated 6.0.0 use {@see \Illuminate\Support\Facades\Crypt::decrypt()} instead.
     */
    public function validateData($data, #[SensitiveParameter] $key = null, $rawHash = false): string|false
    {
        try {
            return Crypt::decrypt($data);
        } catch (DecryptException) {
            return false;
        }
    }

    /**
     * @inheritdoc
     * @param string $data the data to encrypt
     * @param string|null $inputKey the input to use for encryption and authentication
     * @param string $info optional context and application specific information, see [[hkdf()]]
     * @return string the encrypted data
     * @throws InvalidConfigException on OpenSSL not loaded
     * @throws Exception on OpenSSL error
     * @see encryptByPassword()
     * @deprecated 6.0.0 use {@see \Illuminate\Support\Facades\Crypt::encrypt()} instead.
     */
    public function encryptByKey(#[SensitiveParameter] $data, #[SensitiveParameter] $inputKey = null, $info = null): string
    {
        if ($inputKey === null) {
            $inputKey = Cms::config()->securityKey;
        }

        return parent::encryptByKey($data, $inputKey, $info);
    }

    /**
     * @inheritdoc
     * @param string $data the encrypted data to decrypt
     * @param string|null $inputKey the input to use for encryption and authentication
     * @param string $info optional context and application specific information, see [[hkdf()]]
     * @return string|false the decrypted data or false on authentication failure
     * @throws InvalidConfigException on OpenSSL not loaded
     * @throws Exception on OpenSSL error
     */
    public function decryptByKey($data, #[SensitiveParameter] $inputKey = null, $info = null): string|false
    {
        try {
            return Crypt::decrypt($data);
        } catch (DecryptException) {
            if ($inputKey === null) {
                $inputKey = Cms::config()->securityKey;
            }

            return parent::decryptByKey($data, $inputKey, $info);
        }
    }

    /**
     * Returns whether the given key appears to be sensitive.
     *
     * @param string $key
     * @return bool
     * @since 3.7.24
     * @deprecated 6.0.0 use {@see \CraftCms\Cms\Support\Security::isSensitive()} instead.
     */
    public function isSensitive(string $key): bool
    {
        return $this->supportSecurity()->isSensitive($key);
    }

    /**
     * Checks the given key to see if it looks like it contains sensitive info, and if so, redacts the given value.
     *
     * @param string $key
     * @param mixed $value
     * @return mixed The possibly-redacted value
     */
    public function redactIfSensitive(string $key, #[SensitiveParameter] mixed $value): mixed
    {
        return $this->supportSecurity()->redactIfSensitive($key, $value);
    }

    /**
     * Returns whether the given file path is located within or above any system directories.
     *
     * @param string $path
     * @return bool
     * @since 5.4.2
     */
    public function isSystemDir(string $path): bool
    {
        return app(ModernSecurity::class)->isSystemDir($path);
    }

    private function supportSecurity(): ModernSecurity
    {
        return new ModernSecurity($this->sensitiveKeywords);
    }
}
