<?php

declare(strict_types=1);

namespace CraftCms\Cms\Support;

use BackedEnum;
use Craft;
use craft\helpers\HtmlPurifier;
use CraftCms\Cms\Cms;
use HTMLPurifier_Config;
use InvalidArgumentException;
use LitEmoji\LitEmoji;
use Ramsey\Uuid\Validator\GenericValidator;
use ReflectionClass;
use voku\helper\ASCII;
use yii\base\Exception;
use yii\base\InvalidConfigException;

class Str extends \Illuminate\Support\Str
{
    /** @see asciiCharMap() */
    private static ?array $asciiCharMaps = null;

    /** @see escapeShortcodes() */
    private static ?array $shortcodeEscapeMap = null;

    /**
     * Returns ASCII character mappings, merging in any custom defined mappings
     * from the <config5:customAsciiCharMappings> config setting.
     *
     * @param  bool  $flat  Whether the mappings should be returned as a flat array (é => e)
     * @param  string|null  $language  Whether to include language-specific mappings (only applied if $flat is true)
     * @return array The fully merged ASCII character mappings.
     */
    public static function asciiCharMap(bool $flat = false, ?string $language = '*'): array
    {
        $key = $flat ? "flat-$language" : '*';

        if (isset(self::$asciiCharMaps[$key])) {
            return self::$asciiCharMaps[$key];
        }

        $map = ASCII::charsArrayWithSingleLanguageValues(false, false);

        if ($language !== null) {
            /** @var ASCII::*_LANGUAGE_CODE $language */
            $langSpecific = ASCII::charsArrayWithOneLanguage($language, false, false);

            if ($langSpecific !== []) {
                $map = array_merge($map, $langSpecific);
            }
        }

        if ($flat) {
            return self::$asciiCharMaps[$key] = $map;
        }

        $byAscii = [];

        foreach ($map as $char => $ascii) {
            $byAscii[$ascii][] = $char;
        }

        return self::$asciiCharMaps[$key] = $byAscii;
    }

    /**
     * Converts a CamelCase name into space-separated words.
     * For example, 'PostTag' will be converted to 'Post Tag'.
     *
     * @param  ?string  $name  the string to be converted
     * @param  bool  $ucwords  whether to capitalize the first letter in each word
     * @return string the resulting words
     */
    public static function camel2words(?string $name, bool $ucwords = true): string
    {
        if (empty($name)) {
            return (string) $name;
        }

        // Add a space before any uppercase letter preceded by a lowercase letter (xY => x Y)
        // and any uppercase letter preceded by an uppercase letter and followed by a lowercase letter (XYz => X Yz)
        $label = preg_replace('/(?<=\p{Ll})\p{Lu}|(?<=\p{L})\p{Lu}(?=\p{Ll})/u', ' \0', $name);

        $label = mb_strtolower(trim(str_replace(['-', '_', '.'], ' ', $label)));

        return $ucwords ? ucwords($label) : $label;
    }

    /**
     * Detects whether the given string has any 4-byte UTF-8 characters.
     *
     * @param  string  $str  The string to process.
     * @return bool Whether the string contains any 4-byte UTF-8 characters or not.
     */
    public static function containsMb4(string $str): bool
    {
        $length = strlen($str);

        for ($i = 0; $i < $length; $i++) {
            if (ord($str[$i]) >= 240) {
                return true;
            }
        }

        return false;
    }

    /**
     * Attempts to convert a string to UTF-8 and clean any non-valid UTF-8 characters.
     */
    public static function convertToUtf8(string $str): string
    {
        // If it's already a UTF8 string, just clean and return it
        if (mb_check_encoding($str, 'UTF-8')) {
            return HtmlPurifier::cleanUtf8($str);
        }

        // Otherwise set HTMLPurifier to the actual string encoding
        $config = HTMLPurifier_Config::createDefault();
        $config->set('Core.Encoding', static::encoding($str));

        // Clean it
        $str = HtmlPurifier::cleanUtf8($str);

        // Convert it to UTF8 if possible
        if (PHP::checkForValidIconv()) {
            return HtmlPurifier::convertToUtf8($str, $config);
        }

        return mb_convert_encoding($str, 'UTF-8');
    }

    /**
     * Base64-decodes and decrypts a string generated by [[encenc()]].
     *
     * @param  string  $str  The string.
     *
     * @throws InvalidConfigException on OpenSSL not loaded
     * @throws Exception on OpenSSL error
     */
    public static function decdec(string $str): string
    {
        if (str_starts_with($str, 'base64:')) {
            $str = base64_decode(substr($str, 7));
        }

        if (str_starts_with($str, 'crypt:')) {
            return Craft::$app->getSecurity()->decryptByKey(substr($str, 6));
        }

        return $str;
    }

    /**
     * Converts emoji to shortcodes.
     */
    public static function emojiToShortcodes(string $str): string
    {
        // Add delimiters around all 4-byte chars
        $dl = '__MB4_DL__';
        $dr = '__MB4_DR__';

        $str = static::replaceMb4($str, fn ($char) => sprintf('%s%s%s', $dl, $char, $dr));

        // Strip out consecutive delimiters
        $str = str_replace(sprintf('%s%s', $dr, $dl), '', $str);

        // Replace all 4-byte sequences individually
        return preg_replace_callback("/$dl(.+?)$dr/", fn ($m) => LitEmoji::unicodeToShortcode($m[1]), $str);
    }

    /**
     * Encrypts and base64-encodes a string.
     *
     * @param  string  $str  the string
     *
     * @throws InvalidConfigException on OpenSSL not loaded
     * @throws Exception on OpenSSL error
     *
     * @see decdec()
     */
    public static function encenc(string $str): string
    {
        return 'base64:'.base64_encode('crypt:'.Craft::$app->getSecurity()->encryptByKey($str));
    }

    /**
     * HTML-encodes any 4-byte UTF-8 characters.
     *
     * @param  string  $str  The string
     * @return string The string with converted 4-byte UTF-8 characters
     *
     * @see http://stackoverflow.com/a/16496730/1688568
     */
    public static function encodeMb4(string $str): string
    {
        // (Logic pulled from WP's wp_encode_emoji() function)
        // UTF-32's hex encoding is the same as HTML's hex encoding.
        // So, by converting from UTF-8 to UTF-32, we magically
        // get the correct hex encoding.
        return Str::replaceMb4($str, static function ($char) {
            $unpacked = unpack('H*', mb_convert_encoding($char, 'UTF-32', 'UTF-8'));

            return isset($unpacked[1]) ? '&#x'.ltrim((string) $unpacked[1], '0').';' : '';
        });
    }

    /**
     * Gets the encoding of the given string.
     *
     * @param  string  $str  The string to process.
     * @return string The encoding of the string.
     */
    public static function encoding(string $str): string
    {
        return mb_strtolower(mb_detect_encoding($str, mb_detect_order(), true));
    }

    /**
     * Escapes shortcodes.
     *
     * @since 4.5.0
     */
    public static function escapeShortcodes(string $str): string
    {
        $map = self::shortcodeEscapeMap();

        return str_replace(array_keys($map), $map, $str);
    }

    /**
     * Returns the first line of a string.
     */
    public static function firstLine(string $str): string
    {
        return static::lines($str)[0];
    }

    #[\Override]
    public static function flushCache(): void
    {
        parent::flushCache();
        self::$asciiCharMaps = null;
        self::$shortcodeEscapeMap = null;
    }

    /**
     * Converts an email from IDNA ASCII to Unicode, if the server supports IDNA ASCII strings.
     */
    public static function idnToUtf8Email(string $email): string
    {
        if (! PHP::supportsIdn()) {
            return $email;
        }

        if (Cms::config()->useIdnaNontransitionalToUnicode && defined('IDNA_NONTRANSITIONAL_TO_UNICODE')) {
            $variant = IDNA_NONTRANSITIONAL_TO_UNICODE;
        } else {
            $variant = INTL_IDNA_VARIANT_UTS46;
        }

        $parts = explode('@', $email, 2);

        foreach ($parts as &$part) {
            if (($part = idn_to_utf8($part, IDNA_DEFAULT, $variant)) === false) {
                return $email;
            }
        }

        $combined = implode('@', $parts);

        // Return the original string if nothing changed besides casing
        if (strcasecmp($combined, $email) === 0) {
            return $email;
        }

        return $combined;
    }

    /**
     * Indents each line in the given string.
     */
    public static function indent(string $str, string $indent = '    '): string
    {
        return implode("\n", array_map(fn (string $line) => $indent.$line, static::lines($str)));
    }

    /**
     * Inserts $substring into the string at the $index provided.
     *
     * @param  string  $str  The string to insert into.
     * @param  string  $substring  The string to be inserted.
     * @param  int  $index  The 0-based index at which to insert the substring.
     * @return string The resulting string after the insertion
     */
    public static function insert(string $str, string $substring, int $index): string
    {
        if ($index > mb_strlen($str)) {
            return $str;
        }

        return static::substr($str, 0, $index).$substring.static::substr($str, $index);
    }

    /**
     * Returns a regex pattern for invisible characters.
     */
    public static function invisibleCharsPattern(): string
    {
        $invisibleCharCodes = [
            '00ad', // soft hyphen
            '0083', // no break
            '200b', // zero width space
            '200c', // zero width non-joiner
            '200d', // zero width joiner
            '200e', // LTR character
            '200f', // RTL character
            '2062', // invisible times
            '2063', // invisible comma
            '2064', // invisible plus
            'feff', // zero width non-break space
        ];

        array_walk(
            $invisibleCharCodes,
            fn (&$charCode) => $charCode = sprintf('\\x{%s}', $charCode)
        );

        return sprintf('/%s/iu', implode('|', $invisibleCharCodes));
    }

    /**
     * Returns true if the string contains only hexadecimal chars, false otherwise.
     *
     * @param  string  $str  The string to check.
     * @return bool Whether $str contains only hexadecimal chars.
     */
    public static function isHexadecimal(string $str): bool
    {
        return mb_ereg_match('^[[:xdigit:]]*$', $str);
    }

    /**
     * Splits on newlines and carriage returns, returning an array of strings
     * corresponding to the lines in the string.
     *
     * @param  string  $str  The string to split.
     * @return non-empty-array<string> An array of strings.
     */
    public static function lines(string $str): array
    {
        $lines = mb_split("[\r\n]{1,2}", $str);

        if ($lines === false) {
            return [''];
        }

        return $lines;
    }

    /**
     * Generates a random string of latin alphanumeric characters that defaults to a $length of 36. If $extendedChars is
     * set to true, additional symbols can be included in the string. Note that the generated string is *not* a
     * cryptographically secure string. If you need a cryptographically secure string, use
     * [[\craft\services\Security::generateRandomString()|`Craft::$app->security->generateRandomString()`]].
     *
     * @param  int  $length  The length of the random string. Defaults to 36.
     * @param  bool  $extendedChars  Whether to include symbols in the random string.
     * @return string The randomly generated string.
     */
    #[\Override]
    public static function random($length = 36, bool $extendedChars = false): string
    {
        $validChars = $extendedChars
            ? 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`~!@#$%^&*()-_=+[]\{}|;:\'",./<>?"'
            : 'abcdefghijklmnopqrstuvwxyz';

        $string = '';

        $numValidChars = mb_strlen($validChars);

        for ($i = 0; $i < $length; $i++) {
            $string .= $validChars[random_int(0, $numValidChars - 1)];
        }

        return $string;
    }

    /**
     * Replaces 4-byte UTF-8 characters in a string.
     * ---
     * ```php
     * // Convert emojis to smilies
     * $string = StringHelper::replaceMb4($string, function($char) {
     *     switch ($char) {
     *         case '😀':
     *             return ':)';
     *         case '☹️':
     *             return ':(';
     *         default:
     *             return '¯\_(ツ)_/¯';
     *     }
     * });
     * ```
     *
     * @param  string  $str  The string
     * @param  callable|string  $replace  The replacement string, or callback function.
     * @return string The string with converted 4-byte UTF-8 characters
     */
    public static function replaceMb4(string $str, callable|string $replace): string
    {
        $r = preg_replace_callback('/./u', function (array $match) use ($replace): string {
            if (strlen($match[0]) >= 4) {
                return is_callable($replace) ? $replace($match[0]) : $replace;
            }

            return $match[0];
        }, $str);

        if ($r === null) {
            $message = match (preg_last_error()) {
                PREG_BAD_UTF8_ERROR => 'Malformed UTF-8 data',
                default => 'Invalid string',
            };

            throw new InvalidArgumentException($message);
        }

        return $r;
    }

    private static function shortcodeEscapeMap(): array
    {
        if (isset(self::$shortcodeEscapeMap)) {
            return self::$shortcodeEscapeMap;
        }

        $reflectionClass = new ReflectionClass(LitEmoji::class);
        $reflectionMethod = $reflectionClass->getMethod('getShortcodes');
        $shortcodes = array_keys($reflectionMethod->invoke(null));

        self::$shortcodeEscapeMap = array_combine(
            array_map(fn (string $shortcode) => ":$shortcode:", $shortcodes),
            array_map(fn (string $shortcode) => "\\:$shortcode\\:", $shortcodes),
        );

        return self::$shortcodeEscapeMap;
    }

    /**
     * Converts shortcodes to emoji.
     */
    public static function shortcodesToEmoji(string $str): string
    {
        return LitEmoji::shortcodeToUnicode($str);
    }

    /**
     * Splits a string into an array of the words in the string.
     *
     * @param  string  $str  The string
     * @return string[] The words in the string
     */
    public static function splitOnWords(string $str): array
    {
        // Split on anything that is not alphanumeric, or a period, underscore, or hyphen.
        // Reference: http://www.regular-expressions.info/unicode.html
        preg_match_all('/[\p{L}\p{N}\p{M}._-]+/u', $str, $matches);

        return Arr::whereNotEmpty($matches[0]);
    }

    /**
     * Returns a handle-safe version of a string.
     */
    public static function toHandle(string $str): string
    {
        // Remove HTML tags
        $handle = strip_tags($str);

        // Remove inner-word punctuation
        $handle = preg_replace('/[\'"‘’“”ʻ\[\](){}:]/u', '', $handle);

        // Make it lowercase
        $handle = static::lower($handle);

        // Convert extended ASCII characters to basic ASCII
        $handle = static::ascii($handle);

        // Handle must start with a letter
        $handle = preg_replace('/^[^a-z]+/', '', $handle);

        // Replace any remaining non-alphanumeric or underscore characters with spaces
        $handle = preg_replace('/[^a-z0-9_]/', ' ', (string) $handle);

        return static::camel($handle);
    }

    /**
     * Converts an object to its string representation. If the object is an array, will glue the array elements together
     * with the $glue param. Otherwise will cast the object to a string.
     *
     * @param  mixed  $object  The object to convert to a string.
     * @param  string  $glue  The glue to use if the object is an array.
     * @return string The string representation of the object.
     */
    public static function toString(mixed $object, string $glue = ','): string
    {
        if (is_scalar($object) || (is_object($object) && method_exists($object, '__toString'))) {
            return (string) $object;
        }

        if ($object instanceof BackedEnum) {
            return $object->value;
        }

        if (is_iterable($object)) {
            $stringValues = [];

            foreach ($object as $value) {
                if (($value = static::toString($value, $glue)) !== '') {
                    $stringValues[] = $value;
                }
            }

            return implode($glue, $stringValues);
        }

        return '';
    }

    /**
     * Returns an array of words extracted from a string
     *
     * @param  string  $str  The string
     * @param  bool  $lower  Whether the returned words should be lowercased
     * @param  bool  $removePunctuation  Whether punctuation should be removed from the returned words
     * @return string[] The prepped words in the string
     */
    public static function toWords(string $str, bool $lower = false, bool $removePunctuation = false): array
    {
        // Convert CamelCase to multiple words
        // Regex copied from Inflector::camel2words(), but without dropping punctuation
        $str = preg_replace('/(?<!\p{Lu})(\p{Lu})|(\p{Lu})(?=\p{Ll})/u', ' \0', $str);

        if ($lower) {
            // Make it lowercase
            $str = mb_strtolower((string) $str);
        }

        if ($removePunctuation) {
            $str = str_replace(['.', '_', '-'], ' ', $str);
        }

        // Remove inner-word punctuation.
        $str = preg_replace('/[\'"‘’“”ʻ\[\]\(\)\{\}:]/u', '', (string) $str);

        // Split on the words and return
        return static::splitOnWords($str);
    }

    /**
     * Unscapes shortcodes.
     *
     * @since 4.5.0
     */
    public static function unescapeShortcodes(string $str): string
    {
        $map = self::shortcodeEscapeMap();

        return str_replace($map, array_keys($map), $str);
    }

    public static function uuidPattern(): string
    {
        return Str::between((new GenericValidator)->getPattern(), '\A', '\z');
    }
}
