!function(a){Craft.Tool=Garnish.Base.extend({$trigger:null,$form:null,$innerProgressBar:null,toolClass:null,optionsHtml:null,buttonLabel:null,hud:null,totalActions:null,completedActions:null,loadingActions:null,queue:null,init:function(b,c,d,e){this.toolClass=c,this.optionsHtml=d,this.buttonLabel=e,this.$trigger=a("#"+b),this.addListener(this.$trigger,"click","showHUD")},showHUD:function(b){b.stopPropagation(),this.hud?this.hud.show():(this.$form=a('<div class="form"/>').html(this.optionsHtml+'<div class="buttons"><input type="submit" class="btn submit" value="'+this.buttonLabel+'"></div>'),this.hud=new Garnish.HUD(this.$trigger,this.$form,{orientations:["top","bottom","right","left"],hudClass:"hud toolhud",onSubmit:a.proxy(this,"onSubmit")}),Craft.initUiElements(this.$form))},onSubmit:function(b){this.progressBar?this.progressBar.resetProgressBar():this.progressBar=new Craft.ProgressBar(this.hud.$main),this.totalActions=1,this.completedActions=0,this.queue=[],this.loadingActions=0,this.currentBatchQueue=[],this.progressBar.$progressBar.css({top:Math.round(this.hud.$main.outerHeight()/2)-6}).removeClass("hidden"),this.$form.velocity("stop").animateLeft(-200,"fast"),this.progressBar.$progressBar.velocity("stop").animateLeft(30,"fast",a.proxy(function(){var a=Garnish.getPostData(this.$form),b=Craft.expandPostArray(a);b.start=!0,this.loadAction({params:b})},this))},updateProgressBar:function(){var a=100*this.completedActions/this.totalActions;this.progressBar.setProgressPercentage(a)},loadAction:function(a){this.loadingActions++,"undefined"!=typeof a.confirm&&a.confirm?this.showConfirmDialog(a):this.postActionRequest(a.params)},showConfirmDialog:function(b){var c=a('<form class="modal fitted confirmmodal"/>').appendTo(Garnish.$bod),d=a('<div class="body"/>').appendTo(c).html(b.confirm),e=a('<footer class="footer"/>').appendTo(c),f=a('<div class="buttons right"/>').appendTo(e),g=a('<div class="btn">'+Craft.t("app","Cancel")+"</div>").appendTo(f);a('<input type="submit" class="btn submit" value="'+Craft.t("app","OK")+'"/>').appendTo(f);Craft.initUiElements(d);var h=new Garnish.Modal(c,{onHide:a.proxy(this,"onActionResponse")});this.addListener(g,"click",function(){h.hide()}),this.addListener(c,"submit",function(c){c.preventDefault(),h.settings.onHide=a.noop,h.hide();var e=Garnish.getPostData(d),f=Craft.expandPostArray(e);a.extend(f,b.params),this.postActionRequest(f)})},postActionRequest:function(b){var c={tool:this.toolClass,params:b};Craft.postActionRequest("tools/perform-action",c,a.proxy(this,"onActionResponse"),{complete:a.noop})},onActionResponse:function(b,c){
// Add any new batches to the queue?
if(this.loadingActions--,this.completedActions++,"success"==c&&b&&b.batches)for(var d=0;d<b.batches.length;d++)b.batches[d].length&&(this.totalActions+=b.batches[d].length,this.queue.push(b.batches[d]));
// Load as many additional items in the current batch as possible
for(b&&b.error&&alert(b.error),this.updateProgressBar();this.loadingActions<Craft.Tool.maxConcurrentActions&&this.currentBatchQueue.length;)this.loadNextAction();
// Was that the end of the batch?
if(!this.loadingActions)
// Is there another batch?
if(this.queue.length)this.currentBatchQueue=this.queue.shift(),this.loadNextAction();else{if(b&&b.backupFile){var e=a("<iframe/>",{src:Craft.getActionUrl("tools/download-backup-file",{filename:b.backupFile})}).hide();this.$form.append(e)}
// Quick delay so things don't look too crazy.
setTimeout(a.proxy(this,"onComplete"),300)}},loadNextAction:function(){var a=this.currentBatchQueue.shift();this.loadAction(a)},onComplete:function(){this.$allDone||(this.$allDone=a('<div class="alldone" data-icon="done" />').appendTo(this.hud.$main)),this.$allDone.css({top:Math.round(this.hud.$main.outerHeight()/2)-30}),this.progressBar.$progressBar.animateLeft(-170,"fast"),this.$allDone.animateLeft(30,"fast"),
// Just in case the tool created a new task...
Craft.cp.runPendingTasks()}},{maxConcurrentActions:3})}(jQuery);
//# sourceMappingURL=settings.js.map