<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Blocks is already up to date.' => '',
  'Blocks needs to be able to write to the follow files, but can’t: {fileList}' => '',
  'Error in validating the download.' => '',
  'Error: The migration directory “{directory}” does’t exist.' => '',
  'MigrationCommand connectionId “{connectionId}” is invalid. Please make sure it refers to the Id of a DbConnection application component.' => '',
  'The update can’t be installed because Blocks requires MySQL version "{requiredMySqlVersion}" or higher and you have MySQL version "{installedMySqlVersion}" installed.' => '',
  'The update can’t be installed because Blocks requires PHP version "{requiredPhpVersion}" or higher and MySQL version "{requiredMySqlVersion}" or higher.  You have PHP version "{installedPhpVersion}" and MySQL version "{installedMySqlVersion}" installed.' => '',
  'The update can’t be installed because Blocks requires PHP version "{requiredPhpVersion}" or higher and you have PHP version "{installedPhpVersion}" installed.' => '',
  'The update was performed successfully, but there was a problem invalidating the update cache.' => '',
  'The update was performed successfully, but there was a problem setting the new version and build number in the database.' => '',
  'There was a problem backing up your files for the update.' => '',
  'There was a problem downloading the package.' => '',
  'There was a problem unpacking the downloaded package.' => '',
  'There was a problem updating your database.' => '',
  'There was a problem updating your files.' => '',
  'There was a problem validating the downloaded package.' => '',
);
