<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into craft/config/filecache.php, and make your change there.
 */

return array(
	/**
	 * @var boolean whether to use apcu or apc as the underlying caching extension.
	 * If true {@link http://pecl.php.net/package/apcu APCu} will be used.
	 * If false {@link http://pecl.php.net/package/apc APC}. will be used.
	 * Defaults to false.
	 */
	'useApcu' => false,
);
