<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into craft/config/s3assetsource.php, and make your change there.
 */

return array(
	/**
	 * The S3 Asset Source name.
	 */
	'assetSourceName' => 'Amazon S3',
	/**
	 * The S3 Asset Source host.
	 */
    'host' => 'amazonaws.com',
    /**
	 * The S3 Asset Source region - leave empty to use bucket location detection.
	 */
    'region' => '',
    /**
	 * The S3 Asset Source endpoint - {host/region} will be replaced by their configured values.
	 */
    'endpoint' => 's3.{host}',
    /**
	 * The S3 Asset Source endpoint by location - default format if not predefined. {host/location} will be replaced by their configured values.
	 */
    'endpointByLocation' => 's3-{location}.{host}',
	/**
	 * The S3 Asset Source predefined endpoints by location. {host/location} will be replaced by the configured value.
	 */
    'predefinedEndpoints' => array(
		'US' => 's3.{host}',
		'EU' => 's3-eu-west-1.{host}',
	),
    /**
	 * The S3 Asset Source URL prefix - {bucket/host/endpointbyLocation/location} will be replaced by their configured values.
	 */
    'urlPrefix' => 'http://{endpointByLocation}/{bucket}/',
    /**
	 * Force a Content-Length header of zero on empty putObject requests to solve 411 Length Required issues.
	 */
    'putObjectForceContentLength' => 0,
);
