<?php

declare(strict_types=1);

namespace CraftCms\Cms\Field\IdeHelper;

use CraftCms\Cms\Asset\Elements\Asset;
use CraftCms\Cms\Asset\Models\Volume;
use CraftCms\Cms\Cms;
use CraftCms\Cms\Element\ElementCollection;
use CraftCms\Cms\Element\Queries\EntryQuery;
use CraftCms\Cms\Entry\Elements\Entry;
use CraftCms\Cms\Entry\EntryTypes;
use CraftCms\Cms\Field\Contracts\FieldInterface;
use CraftCms\Cms\Field\Fields;
use CraftCms\Cms\Field\Matrix;
use CraftCms\Cms\FieldLayout\FieldLayout;
use CraftCms\Cms\Support\Str;
use Illuminate\Container\Attributes\Singleton;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Symfony\Component\Filesystem\Path;
use Throwable;

#[Singleton]
final readonly class CustomFieldIdeHelperGenerator
{
    public function __construct(
        private Fields $fields,
        private EntryTypes $entryTypes,
    ) {}

    public function generate(): void
    {
        if (! Cms::config()->ideHelperEnabled) {
            return;
        }

        $outputPath = $this->getOutputPath();

        if (! $this->ensureDirectory($outputPath)) {
            return;
        }

        $content = $this->buildHelperContent();

        try {
            File::put($outputPath.'/custom-fields.php', $content);
        } catch (Throwable $e) {
            Log::warning('Failed to write IDE helper file: '.$e->getMessage());
        }
    }

    public function normalizeHandle(string $handle): string
    {
        return Str::studly($handle);
    }

    private function getOutputPath(): string
    {
        $path = Cms::config()->ideHelperPath;

        if (Path::isAbsolute($path)) {
            return $path;
        }

        return base_path($path);
    }

    private function ensureDirectory(string $path): bool
    {
        try {
            File::ensureDirectoryExists($path);

            if (! File::exists($path.'/.gitignore')) {
                File::put($path.'/.gitignore', '*');
            }

            return File::isWritable($path);
        } catch (Throwable $e) {
            Log::warning('IDE helper directory is not writable: '.$e->getMessage());

            return false;
        }
    }

    private function buildHelperContent(): string
    {
        $elementFields = $this->collectFieldsByElement();
        $entryTypeFields = $this->collectFieldsByEntryType();
        $volumeFields = $this->collectFieldsByVolume();

        $lines = [
            '<?php',
            '',
            '/**',
            ' * Custom Field IDE Helper',
            ' *',
            ' * This file is auto-generated by Craft CMS. Do not edit manually.',
            ' * Regenerate via: php craft craft:ide-helper:custom-fields',
            ' *',
            ' * @generated',
            ' */',
            '',
        ];

        // Group all classes by namespace
        $namespaces = [];

        foreach ($elementFields as $elementClass => $fields) {
            if ($elementClass === Entry::class && $entryTypeFields !== []) {
                continue;
            }

            if ($elementClass === Asset::class && $volumeFields !== []) {
                continue;
            }

            $namespace = substr($elementClass, 0, (int) strrpos($elementClass, '\\'));
            $namespaces[$namespace][] = [
                'className' => class_basename($elementClass),
                'fields' => $fields,
                'see' => "\\{$elementClass}",
            ];
        }

        $this->groupSubclasses($namespaces, $entryTypeFields, 'CraftCms\Cms\Entry\Elements', 'Entry');
        $this->groupSubclasses($namespaces, $volumeFields, 'CraftCms\Cms\Asset\Elements', 'Asset');

        // Sort namespaces and classes within each namespace for deterministic output
        ksort($namespaces);
        foreach ($namespaces as &$classes) {
            usort($classes, fn (array $a, array $b) => $a['className'] <=> $b['className']);
        }
        unset($classes);

        // Render one namespace block per namespace
        foreach ($namespaces as $namespace => $classes) {
            $lines[] = "namespace {$namespace} {";

            foreach ($classes as $i => $class) {
                if ($i > 0) {
                    $lines[] = '';
                }

                $hasAnnotations = $class['fields'] !== [] || isset($class['see']);

                if ($hasAnnotations) {
                    $lines[] = '    /**';

                    foreach ($class['fields'] as $handle => $type) {
                        $lines[] = "     * @property {$type} \${$handle}";
                    }

                    if (isset($class['see'])) {
                        $lines[] = '     *';
                        $lines[] = "     * @see {$class['see']}";
                    }

                    $lines[] = '     */';
                }

                $extends = isset($class['extends']) ? " extends {$class['extends']}" : '';
                $lines[] = "    class {$class['className']}{$extends} {}";
            }

            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Group subclass stubs (e.g. Entry types, Asset volumes) into the namespaces map.
     *
     * @param  array<string, list<array{className: string, fields: array<string, string>, extends?: string, see?: string}>>  $namespaces
     * @param  array<string, array<string, string>>  $classFields
     */
    private function groupSubclasses(array &$namespaces, array $classFields, string $namespace, string $parentClass): void
    {
        foreach ($classFields as $className => $fields) {
            $namespaces[$namespace][] = [
                'className' => $className,
                'fields' => $fields,
                'extends' => $parentClass,
            ];
        }
    }

    /**
     * Collect fields grouped by entry type.
     *
     * @return array<string, array<string, string>>
     */
    private function collectFieldsByEntryType(): array
    {
        $result = [];

        foreach ($this->entryTypes->getAllEntryTypes() as $entryType) {
            $layout = $entryType->getFieldLayout();

            if (! $layout) {
                continue;
            }

            $entryTypeHandle = $this->normalizeHandle($entryType->handle);
            $result[$entryTypeHandle] = $this->collectFieldsFromLayout($layout);
        }

        ksort($result);

        return $result;
    }

    /**
     * Collect fields grouped by volume for Asset elements.
     *
     * @return array<string, array<string, string>>
     */
    private function collectFieldsByVolume(): array
    {
        $result = [];

        foreach (Volume::withoutTrashed()->get() as $volume) {
            if ($volume->fieldLayoutId === null) {
                continue;
            }

            if (! $layout = $this->fields->getLayoutById($volume->fieldLayoutId)) {
                continue;
            }

            $className = $this->normalizeHandle($volume->handle).'_Asset';
            $result[$className] = $this->collectFieldsFromLayout($layout);
        }

        ksort($result);

        return $result;
    }

    /**
     * Collect all fields grouped by element class, combining fields from all layouts.
     *
     * @return array<class-string, array<string, string>>
     */
    private function collectFieldsByElement(): array
    {
        $elementFields = [];

        foreach ($this->fields->getAllLayouts() as $layout) {
            $elementFields[$layout->type] = array_merge(
                $elementFields[$layout->type] ?? [],
                $this->collectFieldsFromLayout($layout),
            );
        }

        return array_map(function (array $fields) {
            ksort($fields);

            return $fields;
        }, $elementFields);
    }

    /**
     * Extract field handles and their PHPDoc types from a field layout.
     *
     * @return array<string, string>
     */
    private function collectFieldsFromLayout(FieldLayout $layout): array
    {
        $fields = [];

        foreach ($layout->getCustomFields() as $field) {
            $fields[$field->handle] ??= $this->resolvePhpType($field);
        }

        foreach ($layout->getGeneratedFields() as $generatedField) {
            $handle = $generatedField['handle'] ?? '';
            if ($handle !== '') {
                $fields[$handle] ??= 'string|null';
            }
        }

        ksort($fields);

        return $fields;
    }

    /**
     * Resolve the PHPDoc type for a field, using entry type stubs for Matrix fields.
     */
    private function resolvePhpType(FieldInterface $field): string
    {
        if ($field instanceof Matrix) {
            return $this->resolveMatrixPhpType($field);
        }

        return $this->normalizePhpType($field::phpType());
    }

    /**
     * Resolve the PHPDoc type for a Matrix field using its configured entry types.
     */
    private function resolveMatrixPhpType(Matrix $field): string
    {
        $entryTypes = $field->getEntryTypes();

        if ($entryTypes === []) {
            return $this->normalizePhpType($field::phpType());
        }

        $entryTypeClasses = collect($entryTypes)
            ->map(fn ($entryType) => '\\CraftCms\\Cms\\Entry\\Elements\\'.$this->normalizeHandle($entryType->handle))
            ->sort()
            ->implode('|');

        return sprintf(
            '\\%s<%s>|\\%s<%s>',
            EntryQuery::class,
            $entryTypeClasses,
            ElementCollection::class,
            $entryTypeClasses,
        );
    }

    /**
     * Normalize a PHP type string for PHPDoc.
     */
    private function normalizePhpType(string $type): string
    {
        $types = array_map(function (string $t) {
            $t = trim($t, ' \\');

            if (preg_match('/^(self|static|bool|boolean|int|integer|float|double|string|array|object|callable|callback|iterable|resource|null|mixed|void)(\[\])?$/i', $t)) {
                return $t;
            }

            return '\\'.$t;
        }, explode('|', $type));

        return implode('|', $types);
    }
}
