<?php
defined('BLOCKSBUILDS_PERSONAL_FILENAME') || define('BLOCKSBUILDS_PERSONAL_FILENAME', 'blocks_personal_');
defined('BLOCKSBUILDS_PRO_FILENAME') || define('BLOCKSBUILDS_PRO_FILENAME', 'blocks_pro_');
defined('BLOCKSBUILDS_STANDARD_FILENAME') || define('BLOCKSBUILDS_STANDARD_FILENAME', 'blocks_standard_');

defined('BLOCKS_MIN_PHP_VERSION') || define('BLOCKS_MIN_PHP_VERSION', '5.1.0');
defined('BLOCKS_MIN_MYSQL_VERSION') || define('BLOCKS_MIN_MYSQL_VERSION', '0.0');
defined('BLOCKS_MIN_ORACLE_VERSION') || define('BLOCKS_MIN_ORACLE_VERSION', '0.0');
defined('BLOCKS_MIN_SQLITE_VERSION') || define('BLOCKS_MIN_SQLITE_VERSION', '0.0');
defined('BLOCKS_MIN_POSTGRESQL_VERSION') || define('BLOCKS_MIN_POSTGRESQL_VERSION', '0.0');
defined('BLOCKS_MIN_SQLSERVER_VERSION') || define('BLOCKS_MIN_SQLSERVER_VERSION', '0.0');
