APP_ID=CraftCMS
SECURITY_KEY=UPzGqJJMCTM4n07jkqaFNaVoof6j_Xfo

CRAFT_DB_DRIVER=pgsql
CRAFT_DB_SERVER=127.0.0.1
CRAFT_DB_PORT=5432
CRAFT_DB_DATABASE=craft_test
CRAFT_DB_USER=root
CRAFT_DB_PASSWORD=mysecretpassword
CRAFT_DB_SCHEMA=public

FROM_EMAIL_NAME="Craft CMS"
FROM_EMAIL_ADDRESS=info@craftcms.com
