<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Blocks update at any time.
 *
 * If you want to change any of these settings, copy it into
 * blocks/config/config.php, and make your change there.
 */

/*
 * Determines whether the site is in dev mode or not.
 */
$blocksConfig['devMode'] = false;

/*
 *
 */
$blocksConfig['resourceTriggerWord'] = 'resources';

/*
 *
 */
$blocksConfig['actionTriggerWord'] = 'actions';

/*
 *
 */
$blocksConfig['cacheTimeSeconds'] = 86400;

/*
 *
 */
$blocksConfig['devCacheTimeSeconds'] = 5;

/*
 * How to format the URLs
 *
 * Possible values:
 *  - 'pathinfo' (index.php/path)
 *  - 'querystring' (index.php?p=path)
 *  - 'auto'
 *
 * Note: Not all servers support PATH_INFO. If you're not sure, we recommend you leave this on 'auto'.
 */
$blocksConfig['urlFormat'] = 'auto';

/*
 * The variable to use when specifying paths in the query string (see 'urlFormat')
 */
$blocksConfig['pathVar'] = 'p';
