<?php

use craft\base\ElementInterface;
use craft\elements\Address;
use craft\elements\Asset;
use craft\elements\Entry;
use craft\elements\User;
use craft\models\Site;
use craft\models\UserGroup;

return [
    'allowedTags' => [
        'apply',
        'autoescape',
        'for',
        'if',
        'macro',
        'set',
        'switch',
        'verbatim',
    ],
    'allowedFilters' => [
        'abs',
        'address',
        'append',
        'ascii',
        'base64_encode',
        'batch',
        'boolean',
        'camel',
        'capitalize',
        'column',
        'contains',
        'currency',
        'date',
        'date_modify',
        'datetime',
        'default',
        'diff',
        'duration',
        'e',
        'escape',
        'filesize',
        'filter',
        'filter',
        'filterByValue',
        'find',
        'first',
        'float',
        'format',
        'group',
        'id',
        'index',
        'indexOf',
        'integer',
        'intersect',
        'invoke',
        'join',
        'kebab',
        'keys',
        'last',
        'lcfirst',
        'length',
        'length',
        'lower',
        'map',
        'map',
        'markdown',
        'md',
        'merge',
        'merge',
        'money',
        'multisort',
        'nl2br',
        'number',
        'number_format',
        'pascal',
        'percentage',
        'prepend',
        'push',
        'raw',
        'reduce',
        'reduce',
        'replace',
        'replace',
        'reverse',
        'round',
        'shuffle',
        'slice',
        'sort',
        'spaceless',
        'split',
        'string',
        'striptags',
        't',
        'time',
        'timestamp',
        'title',
        'translate',
        'trim',
        'truncate',
        'ucfirst',
        'ucwords',
        'unique',
        'unshift',
        'upper',
        'url_encode',
        'values',
        'where',
        'widont',
        'without',
        'withoutKey',
    ],
    'allowedFunctions' => [
        'attr',
        'ceil',
        'collect',
        'combine',
        'cpUrl',
        'cycle',
        'dataUrl',
        'date',
        'date',
        'encodeUrl',
        'floor',
        'max',
        'min',
        'ol',
        'random',
        'range',
        'raw',
        'seq',
        'shuffle',
        'siteUrl',
        'svg',
        'tag',
        'timezone_names',
        'ul',
        'url',
        'uuid',
    ],
    'allowedMethods' => [
        Address::class => [
            'getCountryCode',
            'getCountry',
            'getAdministrativeArea',
            'getLocality',
            'getDependentLocality',
            'getPostalCode',
            'getSortingCode',
            'getAddressLine1',
            'getAddressLine2',
            'getOrganization',
            'getGivenName',
            'getAdditionalName',
            'getFamilyName',
            'getLocale',
        ],
        Asset::class => [
            'getDataUrl',
            'getDimensions',
            'getExtension',
            'getFilename',
            'getFormat',
            'getFormattedSize',
            'getFormattedSizeInBytes',
            'getHeight',
            'getImg',
            'getMimeType',
            'getSrcset',
            'getUrlsBySize',
            'getWidth',
        ],
        ElementInterface::class => [
            'getCpEditUrl',
            'getIsHomepage',
            'getLanguage',
            'getLink',
            'getSite',
            'getStatus',
            'getUrl',
        ],
        Entry::class => [
            'getAuthor',
            'getAuthorId',
        ],
        Site::class => [
            'getBaseUrl',
            'getEnabled',
            'getName',
        ],
        User::class => [
            'getAddresses',
            'getFriendlyName',
            'getFullName',
            'getGroups',
            'getName',
            'getPhoto',
            'isInGroup',
        ],
    ],
    'allowedProperties' => [
        Address::class => [
            'latitude',
            'longitude',
            'organizationTaxId',
        ],
        Asset::class => [
            'alt',
            'kind',
            'size',
        ],
        ElementInterface::class => [
            'archived',
            'dateCreated',
            'dateDeleted',
            'dateUpdated',
            'enabled',
            'id',
            'ownerId',
            'siteId',
            'slug',
            'title',
            'trashed',
            'uid',
            'uri',
        ],
        Entry::class => [
            'postDate',
            'expiryDate',
        ],
        Site::class => [
            'handle',
            'hasUrls',
            'id',
            'language',
            'primary',
        ],
        User::class => [
            'active',
            'admin',
            'email',
            'lastLoginDate',
            'locked',
            'pending',
            'photoId',
            'suspended',
            'username',
        ],
        UserGroup::class => [
            'id',
            'name',
            'handle',
            'description',
        ],
    ],
];
