# default Docker DNS server
resolver 127.0.0.11;

# handle requests for healthcheck
server {
    listen 8000;
    listen [::]:8000;
    server_name _;
    location / {
        return 200 'ok';
    }
}

# server configuration for local development
server {
    listen 8080;
    listen [::]:8080;
    access_log /dev/stdout;
    error_log /dev/stderr;
    root /app/web;
    index index.html index.htm index.php;
    server_name _;
    charset utf-8;

    # Healthchecks: Set /ping to be the healhcheck URL
    location /ping {
        access_log off;
        # set max 5 seconds for healthcheck
        fastcgi_read_timeout 5s;
        include fastcgi_params;
        fastcgi_param SCRIPT_NAME /ping;
        fastcgi_param SCRIPT_FILENAME /ping;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
    }

    location / {
        # remove trailing slash
        if ($request_uri ~* ^(.+)/$) {
            return 301 $1;
        }

        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}