<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Attribute “with” not set.' => '',
  'Blocks is already installed.' => '',
  'Could not hash the given password.' => '',
  'GET param “{name}” doesn’t exist.' => '',
  'IsNullOrEmpty requires a string.' => '',
  'No site exists with the Id “{siteId}”.' => '',
  'No user exists with the Id “{userId}”.' => '',
  'No widget exists with the Id “{widgetId}”.' => '',
  'POST param “{name}” doesn’t exist.' => '',
  'Param “{name}” doesn’t exist.' => '',
  'Path to filesystem object isn’t specified within “{methodName}” method.' => '',
  'There is no primary site.' => '',
  'This action may only be performed by admins.' => '',
  'Unable to get directory contents for “{directory}”.' => '',
  'Unable to validate the activation code.' => '',
  '{403message}' => '',
  '{404message}' => '',
  '{500message}' => '',
  '“{className}” doesn’t have an attribute “{attributeName}”.' => '',
);
