<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Blocks update at any time.
 *
 * If you want to change any of these settings, copy it into
 * blocks/config/config.php, and make your change there.
 */

/**
 * Determines whether the site is in dev mode or not.
 */
$blocksConfig['devMode'] = false;

/**
 *
 */
$blocksConfig['resourceTriggerWord'] = 'resource';

/**
 *
 */
$blocksConfig['actionTriggerWord'] = 'action';

/**
 *
 */
$blocksConfig['logoutTriggerWord'] = 'logout';

/**
 * If you're running with devMode = false, this cache time will be used instead of devCacheTimeSeconds.
 */
$blocksConfig['cacheTimeSeconds'] = 86400;

/**
 * If you're running with devMode = true, this cache time will be used instead of cacheTimeSeconds.
 */
$blocksConfig['devCacheTimeSeconds'] = 5;

/**
 * How to format the URLs
 *
 * Possible values:
 *  - 'pathinfo' (index.php/path)
 *  - 'querystring' (index.php?p=path)
 *  - 'auto'
 *
 * Note: Not all servers support PATH_INFO. If you're not sure, we recommend you leave this on 'auto'.
 */
$blocksConfig['urlFormat'] = 'auto';

/**
 * The variable to use when specifying paths in the query string (see 'urlFormat')
 */
$blocksConfig['pathVar'] = 'p';

/**
 * The time a user stays logged in.
 * Valid units of time are:
 * m = minute(s)
 * h = hour(s)
 * d = day(s)
 */
$blocksConfig['sessionTimeout'] = '1h';

/**
 * The length of time a newly generated authorization code will remain active before expiring.
 * Valid units of time are:
 * m = minute(s)
 * h = hour(s)
 * d = day(s)
 */
$blocksConfig['authCodeExpiration'] = '48h';


/**
 * The number of invalid login attempts before the user account is locked.
 */
$blocksConfig['maxInvalidPasswordAttempts'] = 4;

// PHPPass Config

/**
 * Controls the number of iterations for key stretching. A setting of 8 means the hash algorithm will be applied 2^8 = 256 times.
 * This setting should be kept between 4 and 31.
 */
$blocksConfig['phpPass-iterationCount'] = 8;

/**
 * Controls whether portable hashes should be used or not. Portable hashes are salted MD5 hashes prefixed by $P$.
 */
$blocksConfig['phpPass-portableHashes'] = false;
