<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Blocks update at any time.
 *
 * If you want to change any of these settings, copy it into
 * blocks/config/db.php, and make your change there.
 */

/*
 * The database server name or IP address
 */
$db['server'] = 'localhost';

/**
 * The database server port
 */
$db['port'] = '3306';

/*
 * The database username to connect with
 */
$db['user'] = 'root';

/*
 * The database password to connect with
 */
$db['password'] = '';

/*
 * The database name to select
 */
$db['database'] = '';

/*
 * The prefix to use when naming tables
 */
$db['tablePrefix'] = 'blx';

/**
 * The charset to use when creating tables
 */
$db['charset'] = 'utf8';

/**
 * The collation to use when creating tables
 */
$db['collation'] = 'utf8_general_ci';
