<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into `config/db.php`, and make your change there.
 */

return [

    /**
     * The database server name or IP address. Usually 'localhost' or '127.0.0.1'.
     */
    'server' => 'localhost',
    /**
     * The database server port. Defaults to 3306 for MySQL and 5432 for PostgreSQL.
     */
    'port' => '6379',
    /**
     * The name of the database to select.
     */
    'database' => '0'
];
