<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into `config/db.php`, and make your change there.
 */

return [

    /**
     * The redis hostname. Usually 'localhost' or '127.0.0.1'.
     */
    'hostname' => 'localhost',
    /**
     * The redis server port. Defaults to 6379.
     */
    'port' => '6379',
    /**
     * The name of the database to select.
     */
    'database' => '0'
];
