services:
  #  postgres:
  #    env_file: ../../tests-playwright/.env
  #    image: postgres:14-alpine
  #    ports:
  #      - ${CRAFT_DB_PORT:-54329}:5432
  #    environment:
  #      POSTGRES_PASSWORD: ${CRAFT_DB_PASSWORD:-craft}
  #      POSTGRES_USER: ${CRAFT_DB_USER:-craft}
  #      POSTGRES_DB: ${CRAFT_DB_DATABASE:-craft_test}
  #    healthcheck:
  #      test: ['CMD', 'pg_isready', '-U', 'craft', '-d', 'craft_test']
  #      interval: 5s
  #      retries: 3
  mysql:
    image: mysql:8.0
    ports:
      - ${MYSQL_EXTERNAL_PORT:-33069}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${CRAFT_DB_PASSWORD:-craft}
      MYSQL_DATABASE: ${CRAFT_DB_DATABASE:-craft_test}
      MYSQL_USER: ${CRAFT_DB_USER:-craft}
      MYSQL_PASSWORD: ${CRAFT_DB_PASSWORD:-craft}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      interval: 10s
      retries: 5
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
  playwright:
    build:
      target: craft
    ports:
      - ${SITE_PORT:-8089}:8080
    environment:
      CRAFT_APP_ID: ${CRAFT_APP_ID:-CraftCMS}
      CRAFT_ENVIRONMENT: ${CRAFT_ENVIRONMENT:-dev}
      CRAFT_SECURITY_KEY: ${CRAFT_SECURITY_KEY:-1234567890}
      CRAFT_CP_TRIGGER: ${CRAFT_CP_TRIGGER:-admin}

      # pgsql start
      #      CRAFT_DB_DRIVER: ${CRAFT_DB_DRIVER:-pgsql}
      #      CRAFT_DB_SERVER: ${CRAFT_DB_SERVER:-postgres}
      #      CRAFT_DB_PORT: ${CRAFT_DB_PORT:-5432}
      # pgsql end

      # mysql start
      CRAFT_DB_DRIVER: ${CRAFT_DB_DRIVER:-mysql}
      CRAFT_DB_SERVER: ${CRAFT_DB_SERVER:-mysql}
      CRAFT_DB_PORT: ${CRAFT_DB_PORT:-3306}
      # mysql end

      CRAFT_DB_DATABASE: ${CRAFT_DB_DATABASE:-craft_test}
      CRAFT_DB_USER: ${CRAFT_DB_USER:-craft}
      CRAFT_DB_PASSWORD: ${CRAFT_DB_PASSWORD:-craft}
      CRAFT_DB_SCHEMA: ${CRAFT_DB_SCHEMA:-public}
      CRAFT_DB_TABLE_PREFIX: ${CRAFT_DB_TABLE_PREFIX:-}
      PRIMARY_SITE_URL: ${SITE_DOMAIN:-http://127.0.0.1/}

      CODECEPTION_FIXTURES_NAMESPACE: ${CODECEPTION_FIXTURES_NAMESPACE}
      CODECEPTION_FIXTURES_PATH: ${CODECEPTION_FIXTURES_PATH}
    depends_on:
      #      postgres:
      #        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ${REPO_PATH}:/app/repos/repo/
      - ./docker/webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/webserver/supervisord.d/nginx.ini:/etc/supervisord.d/nginx.ini
