<?php

declare(strict_types=1);

namespace CraftCms\Cms\Asset\Elements;

use CraftCms\Cms\Database\Queries\AssetQuery;
use Override;

/**
 * @TODO: Port Asset element fully
 */
final class Asset extends \craft\elements\Asset
{
    #[Override]
    public static function find(): AssetQuery
    {
        return new AssetQuery;
    }

    #[Override]
    public static function findOne(mixed $criteria = null): ?static
    {
        return parent::findOne($criteria); // TODO: Change the autogenerated stub
    }
}
