<?php

/**
 * @link https://github.com/yii2tech
 *
 * @copyright Copyright (c) 2019 Yii2tech
 * @license [New BSD License](http://www.opensource.org/licenses/bsd-license.php)
 */

namespace CraftCms\Yii2Adapter\Web;

use Craft;
use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\Response as IlluminateResponse;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Throwable;
use Yii;
use yii\web\Cookie as YiiCookie;
use yii\web\HeadersAlreadySentException;
use Yii2tech\Illuminate\Http\YiiApplicationMiddleware;

/**
 * Response fills up Laravel HTTP response instead of sending itself back to the user agent.
 *
 * This class allows Laravel middleware to perform post processing for the responses generated by Yii.
 *
 * Application configuration example:
 *
 * ```php
 * return [
 *     'components' => [
 *         'response' => CraftCms\Cms\Yii\Web\Response::class,
 *         // ...
 *     ],
 *     // ...
 * ];
 * ```
 *
 * Usage of this component also allows returning of the response generated by Laravel from Yii controller. For example:
 *
 * ```php
 * class FooController extends \yii\web\Controller
 * {
 *     public function actionFoo()
 *     {
 *         // ...
 *         return Yii::$app->response->setIlluminateResponse(redirect('foo/create')->withInput());
 *     }
 * }
 * ```
 *
 * @see IlluminateResponse
 * @see YiiApplicationMiddleware
 *
 * @property SymfonyResponse $illuminateResponse related Laravel response.
 *
 * @author Paul Klimov <klimov.paul@gmail.com>
 *
 * @since 1.0
 */
class Response extends \yii\web\Response implements Responsable
{
    /**
     * @var SymfonyResponse|null related Laravel response.
     */
    private $_illuminateResponse;

    private bool $_illuminateResponseInjected = false;

    private bool $_illuminateResponsePrepared = false;

    /**
     * @param  bool  $create  whether to create a response, if it is empty.
     */
    public function getIlluminateResponse(bool $create = false): ?SymfonyResponse
    {
        if ($create && !$this->_illuminateResponsePrepared) {
            if ($this->_illuminateResponse === null) {
                $this->prepare();
            }

            if ($this->_illuminateResponse === null) {
                $this->_illuminateResponse = new StreamedResponse($this->stream === null ? null : function() {
                    parent::sendContent();
                });
            }

            if (!$this->_illuminateResponseInjected) {
                $this->sendHeaders();

                if (!$this->_illuminateResponse instanceof StreamedResponse) {
                    $this->sendContent();
                }
            }

            $this->_illuminateResponsePrepared = true;
        }

        return $this->_illuminateResponse;
    }

    protected function createIlluminateResponse(): IlluminateResponse
    {
        return app()->make(IlluminateResponse::class);
    }

    public function setIlluminateResponse(SymfonyResponse $response): static
    {
        $this->_illuminateResponse = $response;
        $this->_illuminateResponseInjected = true;
        $this->_illuminateResponsePrepared = true;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function clear(): void
    {
        parent::clear();

        $this->_illuminateResponse = null;
        $this->_illuminateResponseInjected = false;
        $this->_illuminateResponsePrepared = false;
    }

    /**
     * {@inheritdoc}
     */
    public function send(): void
    {
        if ($this->getIlluminateResponse() !== null) {
            $this->isSent = true;

            return;
        }

        parent::send();

        Craft::$app->getSession()->updateFlashCounters();
    }

    /**
     * {@inheritdoc}
     */
    protected function prepare(): void
    {
        if ($this->stream === null) {
            // avoid usage of response bridge for file sending, since it may cause PHP memory error.
            $response = $this->getIlluminateResponse();
            if ($response === null) {
                $this->_illuminateResponse = $this->createIlluminateResponse();
            }
        }

        parent::prepare();
    }

    /**
     * {@inheritdoc}
     */
    protected function sendHeaders(): void
    {
        $response = $this->getIlluminateResponse();
        if ($response === null) {
            parent::sendHeaders();

            return;
        }

        if (headers_sent($file, $line)) {
            throw new HeadersAlreadySentException($file, $line);
        }

        $response->setProtocolVersion($this->version);
        $response->setStatusCode($this->getStatusCode(), $this->statusText);

        foreach ($this->getHeaders() as $name => $values) {
            $response->headers->set($name, $values);
        }

        $this->sendCookies();
    }

    /**
     * {@inheritdoc}
     */
    protected function sendCookies(): void
    {
        $response = $this->getIlluminateResponse();
        if ($response === null) {
            parent::sendCookies();

            return;
        }

        foreach ($this->getCookies() as $cookie) {
            $response->headers->setCookie(self::illuminateCookie($cookie));
        }
    }

    /**
     * A Yii response cookie as its Symfony equivalent.
     *
     * Shared by both exits into Laravel — the send path above and
     * {@see self::toResponse()} — so what a cookie carries can't depend on
     * which one a response happens to leave through.
     *
     * `sameSite` is included because Craft configures it
     * (`Craft::cookieConfig()` reads `sameSiteCookieValue`); omitting it let
     * Symfony apply its own `Lax` default, so a project asking for `Strict` or
     * `None` silently got neither — and a project configuring nothing got an
     * explicit `Lax` that Craft never asked for. Passing it through matches
     * Yii's own `sendCookies()`, which emits no attribute at all for an empty
     * value. Symfony lowercases the value and maps an empty string to null.
     */
    private static function illuminateCookie(YiiCookie $cookie): Cookie
    {
        return new Cookie(
            $cookie->name,
            $cookie->value,
            $cookie->expire,
            $cookie->path,
            $cookie->domain,
            $cookie->secure,
            $cookie->httpOnly,
            raw: false,
            sameSite: $cookie->sameSite,
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function sendContent(): void
    {
        $response = $this->getIlluminateResponse();
        if ($response === null) {
            parent::sendContent();

            return;
        }

        if ($this->stream === null) {
            $response->setContent($this->content);

            return;
        }

        ob_start();
        ob_implicit_flush(false);

        try {
            parent::sendContent();

            $response->setContent(ob_get_clean());
        } catch (Throwable $e) {
            if (!@ob_end_clean()) {
                ob_clean();
            }
            throw $e;
        }
    }

    /**
     * {@inheritdoc}
     *
     * This exit and the send path have to agree about what a response carries.
     * They didn't: this one copied content, status and headers and dropped the
     * cookies {@see self::sendCookies()} carries across, so a legacy controller
     * setting a cookie on its response lost it whenever Laravel resolved the
     * response through `Responsable` rather than through the Yii send path. An
     * OAuth flow keeping its state in a cookie could never complete.
     *
     * The mapping itself lives in {@see self::illuminateCookie()}, shared with
     * the send path so the two can't drift apart again.
     *
     * Deliberately still assembles its own response rather than delegating to
     * {@see self::getIlluminateResponse()}: that would also run
     * {@see self::sendHeaders()}, which throws once headers are sent — a
     * failure mode this method has never had, and which `LegacyMiddleware`
     * guards against separately.
     *
     * Known gap: a streamed response (`sendFile()` and friends) still arrives
     * here as its empty `content`. Use the send path for those.
     */
    public function toResponse($request): IlluminateResponse
    {
        $response = new IlluminateResponse(
            content: $this->content,
            status: $this->getStatusCode(),
            headers: $this->getHeaders()->toArray()
        );

        foreach ($this->getCookies() as $cookie) {
            $response->headers->setCookie(self::illuminateCookie($cookie));
        }

        return $response;
    }
}
