import {writeFileSync} from 'fs';
import {dirname, resolve} from 'path';
import {fileURLToPath} from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT_FILE = resolve(ROOT, 'src/styles/shared/colorable.css');

/*
This is the same as the colors in constants/colors but we can't import
typescript into this JS file so we had to duplicate for now.
 */
const availableColors = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
  'white',
  'gray',
  'black',
];

function lightScale(color) {
  if (color === 'white') {
    return {
      fillQuiet: 'var(--color-white)',
      borderQuiet: 'var(--color-gray-200)',
      onQuiet: 'var(--color-gray-800)',
    };
  }
  if (color === 'black') {
    return {
      fillQuiet: 'var(--color-gray-900)',
      borderQuiet: 'var(--color-gray-800)',
      onQuiet: 'var(--color-gray-100)',
    };
  }
  return {
    fillQuiet: `var(--color-${color}-50)`,
    borderQuiet: `var(--color-${color}-300)`,
    onQuiet: `var(--color-${color}-800)`,
  };
}

function darkScale(color) {
  if (color === 'white') {
    return {
      fillQuiet: 'var(--color-gray-800)',
      borderQuiet: 'var(--color-gray-700)',
      onQuiet: 'var(--color-gray-200)',
    };
  }
  if (color === 'black') {
    return {
      fillQuiet: 'var(--color-gray-950)',
      borderQuiet: 'var(--color-gray-800)',
      onQuiet: 'var(--color-gray-300)',
    };
  }
  return {
    fillQuiet: `var(--color-${color}-950)`,
    borderQuiet: `var(--color-${color}-800)`,
    onQuiet: `var(--color-${color}-300)`,
  };
}

function buildTokens(colors, scaleFn) {
  return colors
    .map((color) => {
      const s = scaleFn(color);
      return [
        `  --c-color-${color}-fill-quiet: ${s.fillQuiet};`,
        `  --c-color-${color}-border-quiet: ${s.borderQuiet};`,
        `  --c-color-${color}-on-quiet: ${s.onQuiet};`,
      ].join('\n');
    })
    .join('\n\n');
}

function buildStyleBlock(color) {
  return `.c-colorable--${color},
[data-color='${color}'] {
  --c-color-fill-quiet: var(--c-color-${color}-fill-quiet);
  --c-color-border-quiet: var(--c-color-${color}-border-quiet);
  --c-color-on-quiet: var(--c-color-${color}-on-quiet);
}`;
}

function generateStyles(colors) {
  return `/* Auto-generated by scripts/generate-colors.ts — do not edit manually */

:root {
--c-color-fill-quiet: 
${buildTokens(colors, lightScale)}
}

[data-theme='dark'] {
${buildTokens(colors, darkScale)}
}

.c-colorable,
[data-color] {
  --c-color-fill-quiet: var(--c-color-neutral-fill-quiet);
  --c-color-fill-normal: var(--c-color-neutral-fill-quiet);
  --c-color-fill-loud: var(--c-color-neutral-fill-quiet);
  --c-color-border-quiet: var(--c-color-neutral-border-quiet);
  --c-color-border-normal: var(--c-color-neutral-border-quiet);
  --c-color-border-loud: var(--c-color-neutral-border-quiet);
  --c-color-on-quiet: var(--c-color-neutral-on-quiet);
  --c-color-on-normal: var(--c-color-neutral-on-quiet);
  --c-color-on-loud: var(--c-color-neutral-on-quiet);
  
  background-color: var(--c-color-fill-quiet);
  border-color: var(--c-color-border-quiet);
  color: var(--c-color-text-quiet);
}

${colors.map((c) => buildStyleBlock(c)).join('\n')}
`;
}

const css = generateStyles(availableColors);
writeFileSync(OUT_FILE, css);
console.log(`Generated ${OUT_FILE}`);
