#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file.
 *
 * @link http://buildwithcraft.com/
 * @copyright Copyright (c) 2015 Pixel & Tonic, Inc.
 * @license http://buildwithcraft.com/license
 */

// Set this early.
date_default_timezone_set('UTC');

$appType = 'console';
$app = require 'bootstrap.php';
$exitCode = $app->run();
exit($exitCode);
