<?php

declare(strict_types=1);

namespace CraftCms\Yii2Adapter\Form;

/** @internal */
class LegacyConditionClasses
{
    public const array CORE_CLASSES = [
        \craft\elements\conditions\addresses\AddressCondition::class => \CraftCms\Cms\Address\Conditions\AddressCondition::class,
        \craft\elements\conditions\addresses\AddressLine1ConditionRule::class => \CraftCms\Cms\Address\Conditions\AddressLine1ConditionRule::class,
        \craft\elements\conditions\addresses\AddressLine2ConditionRule::class => \CraftCms\Cms\Address\Conditions\AddressLine2ConditionRule::class,
        \craft\elements\conditions\addresses\AddressLine3ConditionRule::class => \CraftCms\Cms\Address\Conditions\AddressLine3ConditionRule::class,
        \craft\elements\conditions\addresses\AdministrativeAreaConditionRule::class => \CraftCms\Cms\Address\Conditions\AdministrativeAreaConditionRule::class,
        \craft\elements\conditions\addresses\CountryConditionRule::class => \CraftCms\Cms\Address\Conditions\CountryConditionRule::class,
        \craft\elements\conditions\addresses\DependentLocalityConditionRule::class => \CraftCms\Cms\Address\Conditions\DependentLocalityConditionRule::class,
        \craft\elements\conditions\addresses\FieldConditionRule::class => \CraftCms\Cms\Address\Conditions\FieldConditionRule::class,
        \craft\elements\conditions\addresses\FullNameConditionRule::class => \CraftCms\Cms\Address\Conditions\FullNameConditionRule::class,
        \craft\elements\conditions\addresses\LocalityConditionRule::class => \CraftCms\Cms\Address\Conditions\LocalityConditionRule::class,
        \craft\elements\conditions\addresses\OrganizationConditionRule::class => \CraftCms\Cms\Address\Conditions\OrganizationConditionRule::class,
        \craft\elements\conditions\addresses\OrganizationTaxIdConditionRule::class => \CraftCms\Cms\Address\Conditions\OrganizationTaxIdConditionRule::class,
        \craft\elements\conditions\addresses\PostalCodeConditionRule::class => \CraftCms\Cms\Address\Conditions\PostalCodeConditionRule::class,
        \craft\elements\conditions\addresses\SortingCodeConditionRule::class => \CraftCms\Cms\Address\Conditions\SortingCodeConditionRule::class,
        \craft\elements\conditions\assets\AssetCondition::class => \CraftCms\Cms\Asset\Conditions\AssetCondition::class,
        \craft\elements\conditions\assets\DateModifiedConditionRule::class => \CraftCms\Cms\Asset\Conditions\DateModifiedConditionRule::class,
        \craft\elements\conditions\assets\FilenameConditionRule::class => \CraftCms\Cms\Asset\Conditions\FilenameConditionRule::class,
        \craft\elements\conditions\assets\FileSizeConditionRule::class => \CraftCms\Cms\Asset\Conditions\FileSizeConditionRule::class,
        \craft\elements\conditions\assets\FileTypeConditionRule::class => \CraftCms\Cms\Asset\Conditions\FileTypeConditionRule::class,
        \craft\elements\conditions\assets\HasAltConditionRule::class => \CraftCms\Cms\Asset\Conditions\HasAltConditionRule::class,
        \craft\elements\conditions\assets\HeightConditionRule::class => \CraftCms\Cms\Asset\Conditions\HeightConditionRule::class,
        \craft\elements\conditions\assets\EditableConditionRule::class => \CraftCms\Cms\Asset\Conditions\SavableConditionRule::class,
        \craft\elements\conditions\assets\SavableConditionRule::class => \CraftCms\Cms\Asset\Conditions\SavableConditionRule::class,
        \craft\elements\conditions\assets\UploaderConditionRule::class => \CraftCms\Cms\Asset\Conditions\UploaderConditionRule::class,
        \craft\elements\conditions\assets\ViewableConditionRule::class => \CraftCms\Cms\Asset\Conditions\ViewableConditionRule::class,
        \craft\elements\conditions\assets\VolumeConditionRule::class => \CraftCms\Cms\Asset\Conditions\VolumeConditionRule::class,
        \craft\elements\conditions\assets\WidthConditionRule::class => \CraftCms\Cms\Asset\Conditions\WidthConditionRule::class,
        \craft\base\conditions\BaseCondition::class => \CraftCms\Cms\Condition\BaseCondition::class,
        \craft\base\conditions\BaseConditionRule::class => \CraftCms\Cms\Condition\BaseConditionRule::class,
        \craft\base\conditions\BaseDateRangeConditionRule::class => \CraftCms\Cms\Condition\BaseDateRangeConditionRule::class,
        \craft\base\conditions\BaseElementSelectConditionRule::class => \CraftCms\Cms\Condition\BaseElementSelectConditionRule::class,
        \craft\base\conditions\BaseLightswitchConditionRule::class => \CraftCms\Cms\Condition\BaseLightswitchConditionRule::class,
        \craft\base\conditions\BaseMultiSelectConditionRule::class => \CraftCms\Cms\Condition\BaseMultiSelectConditionRule::class,
        \craft\base\conditions\BaseNumberConditionRule::class => \CraftCms\Cms\Condition\BaseNumberConditionRule::class,
        \craft\base\conditions\BaseSelectConditionRule::class => \CraftCms\Cms\Condition\BaseSelectConditionRule::class,
        \craft\base\conditions\BaseTextConditionRule::class => \CraftCms\Cms\Condition\BaseTextConditionRule::class,
        \craft\elements\conditions\DateCreatedConditionRule::class => \CraftCms\Cms\Element\Conditions\DateCreatedConditionRule::class,
        \craft\elements\conditions\DateUpdatedConditionRule::class => \CraftCms\Cms\Element\Conditions\DateUpdatedConditionRule::class,
        \craft\elements\conditions\ElementCondition::class => \CraftCms\Cms\Element\Conditions\ElementCondition::class,
        \craft\elements\conditions\HasDescendantsRule::class => \CraftCms\Cms\Element\Conditions\HasDescendantsRule::class,
        \craft\elements\conditions\HasUrlConditionRule::class => \CraftCms\Cms\Element\Conditions\HasUrlConditionRule::class,
        \craft\elements\conditions\IdConditionRule::class => \CraftCms\Cms\Element\Conditions\IdConditionRule::class,
        \craft\elements\conditions\LanguageConditionRule::class => \CraftCms\Cms\Element\Conditions\LanguageConditionRule::class,
        \craft\elements\conditions\LevelConditionRule::class => \CraftCms\Cms\Element\Conditions\LevelConditionRule::class,
        \craft\elements\conditions\NotRelatedToConditionRule::class => \CraftCms\Cms\Element\Conditions\NotRelatedToConditionRule::class,
        \craft\elements\conditions\RelatedToConditionRule::class => \CraftCms\Cms\Element\Conditions\RelatedToConditionRule::class,
        \craft\elements\conditions\SiteConditionRule::class => \CraftCms\Cms\Element\Conditions\SiteConditionRule::class,
        \craft\elements\conditions\SiteGroupConditionRule::class => \CraftCms\Cms\Element\Conditions\SiteGroupConditionRule::class,
        \craft\elements\conditions\SlugConditionRule::class => \CraftCms\Cms\Element\Conditions\SlugConditionRule::class,
        \craft\elements\conditions\StatusConditionRule::class => \CraftCms\Cms\Element\Conditions\StatusConditionRule::class,
        \craft\elements\conditions\TitleConditionRule::class => \CraftCms\Cms\Element\Conditions\TitleConditionRule::class,
        \craft\elements\conditions\UriConditionRule::class => \CraftCms\Cms\Element\Conditions\UriConditionRule::class,
        \craft\elements\conditions\entries\AuthorConditionRule::class => \CraftCms\Cms\Entry\Conditions\AuthorConditionRule::class,
        \craft\elements\conditions\entries\AuthorGroupConditionRule::class => \CraftCms\Cms\Entry\Conditions\AuthorGroupConditionRule::class,
        \craft\elements\conditions\entries\EntryCondition::class => \CraftCms\Cms\Entry\Conditions\EntryCondition::class,
        \craft\elements\conditions\entries\ExpiryDateConditionRule::class => \CraftCms\Cms\Entry\Conditions\ExpiryDateConditionRule::class,
        \craft\elements\conditions\entries\PostDateConditionRule::class => \CraftCms\Cms\Entry\Conditions\PostDateConditionRule::class,
        \craft\elements\conditions\entries\EditableConditionRule::class => \CraftCms\Cms\Entry\Conditions\SavableConditionRule::class,
        \craft\elements\conditions\entries\SavableConditionRule::class => \CraftCms\Cms\Entry\Conditions\SavableConditionRule::class,
        \craft\elements\conditions\entries\SectionConditionRule::class => \CraftCms\Cms\Entry\Conditions\SectionConditionRule::class,
        \craft\elements\conditions\entries\TypeConditionRule::class => \CraftCms\Cms\Entry\Conditions\TypeConditionRule::class,
        \craft\elements\conditions\entries\ViewableConditionRule::class => \CraftCms\Cms\Entry\Conditions\ViewableConditionRule::class,
        \craft\fields\conditions\CountryFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\CountryFieldConditionRule::class,
        \craft\fields\conditions\DateFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\DateFieldConditionRule::class,
        \craft\fields\conditions\EmptyFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\EmptyFieldConditionRule::class,
        \craft\fields\conditions\GeneratedFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\GeneratedFieldConditionRule::class,
        \craft\fields\conditions\LightswitchFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\LightswitchFieldConditionRule::class,
        \craft\fields\conditions\LinkFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\LinkFieldConditionRule::class,
        \craft\fields\conditions\MoneyFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\MoneyFieldConditionRule::class,
        \craft\fields\conditions\NumberFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\NumberFieldConditionRule::class,
        \craft\fields\conditions\OptionsFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\OptionsFieldConditionRule::class,
        \craft\fields\conditions\RelationalFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\RelationalFieldConditionRule::class,
        \craft\fields\conditions\TextFieldConditionRule::class => \CraftCms\Cms\Field\Conditions\TextFieldConditionRule::class,
        \craft\elements\conditions\users\AdminConditionRule::class => \CraftCms\Cms\User\Conditions\AdminConditionRule::class,
        \craft\elements\conditions\users\AffiliatedSiteConditionRule::class => \CraftCms\Cms\User\Conditions\AffiliatedSiteConditionRule::class,
        \craft\elements\conditions\users\CredentialedConditionRule::class => \CraftCms\Cms\User\Conditions\CredentialedConditionRule::class,
        \craft\elements\conditions\users\EmailConditionRule::class => \CraftCms\Cms\User\Conditions\EmailConditionRule::class,
        \craft\elements\conditions\users\FirstNameConditionRule::class => \CraftCms\Cms\User\Conditions\FirstNameConditionRule::class,
        \craft\elements\conditions\users\GroupConditionRule::class => \CraftCms\Cms\User\Conditions\GroupConditionRule::class,
        \craft\elements\conditions\users\LastLoginDateConditionRule::class => \CraftCms\Cms\User\Conditions\LastLoginDateConditionRule::class,
        \craft\elements\conditions\users\LastNameConditionRule::class => \CraftCms\Cms\User\Conditions\LastNameConditionRule::class,
        \craft\elements\conditions\users\UserCondition::class => \CraftCms\Cms\User\Conditions\UserCondition::class,
        \craft\elements\conditions\users\UsernameConditionRule::class => \CraftCms\Cms\User\Conditions\UsernameConditionRule::class,
    ];
}
