name: facades

on:
  push:
    branches:
      - main
      - '*.x'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    name: Facade DocBlocks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: :php-psr
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_token }}"
                }
              }
            }

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer config repositories.facade-documenter vcs git@github.com:laravel/facade-documenter.git
            composer require --dev laravel/facade-documenter:dev-main --prefer-stable --prefer-dist --no-interaction --no-progress -W

      - name: Update facade docblocks
        run: |
          php -f vendor/bin/facade.php -- \
            CraftCms\\Cms\\Support\\Facades\\Announcements \
            CraftCms\\Cms\\Support\\Facades\\Deprecator \
            CraftCms\\Cms\\Support\\Facades\\EntryTypes \
            CraftCms\\Cms\\Support\\Facades\\Fields \
            CraftCms\\Cms\\Support\\Facades\\I18N \
            CraftCms\\Cms\\Support\\Facades\\ProjectConfig \
            CraftCms\\Cms\\Support\\Facades\\Sections \
            CraftCms\\Cms\\Support\\Facades\\Structures \
            CraftCms\\Cms\\Support\\Facades\\Updates \
            CraftCms\\Cms\\Support\\Facades\\UserGroups

      - name: Commit facade docblocks
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update facade docblocks
          file_pattern: src/
