name: 'ci / Front End'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 6.x
  pull_request:

concurrency:
  group: js-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: 'Code Quality / ESLint'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint:js
