name: monorepo-split

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 6.x
      - feature/split-packages
    tags: '*'

permissions:
  contents: read

concurrency:
  group: monorepo-split-${{ github.ref }}
  cancel-in-progress: true

jobs:
  split-monorepo:
    name: Split monorepo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      # No tag
      - name: Monorepo Split
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@ac9845270ef47266435b4f124b133a323619e738 # v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          package_directory: 'yii2-adapter'
          repository_organization: 'craftcms'
          repository_name: 'yii2-adapter'
          branch: ${{ github.head_ref || github.ref_name }}
          user_name: 'shinybrad'
          user_email: 'shinybrad@pixelandtonic.com'

      # With Tag
      - name: Monorepo Split
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@ac9845270ef47266435b4f124b133a323619e738 # v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'yii2-adapter'
          repository_organization: 'craftcms'
          repository_name: 'yii2-adapter'
          user_name: 'shinybrad'
          user_email: 'shinybrad@pixelandtonic.com'
