name: Sync CMS Assets

on:
  workflow_dispatch:
  push:
    branches:
      - 6.x
      - feature/icons-to-cms-assets
    tags:
      - '*'

permissions:
  contents: read

jobs:
  sync:
    name: Sync CMS assets
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Copy icons
        run: php ./scripts/copyicons.php
      
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Build assets
        run: |
          rm -rf cms-assets/resources
          npm run build:all

          test -f cms-assets/resources/build/manifest.json || { echo "::error::Missing cms-assets/resources/build/manifest.json"; exit 1; }
          test -f cms-assets/resources/legacy/cp/dist/cp.js || { echo "::error::Missing cms-assets/resources/legacy/cp/dist/cp.js"; exit 1; }
          test -f cms-assets/resources/legacy/cp/dist/css/cp.css || { echo "::error::Missing cms-assets/resources/legacy/cp/dist/css/cp.css"; exit 1; }

      - name: Monorepo Split
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          package_directory: 'cms-assets'
          repository_organization: 'craftcms'
          repository_name: 'cms-assets'
          branch: ${{ github.head_ref || github.ref_name }}
          user_name: 'shinybrad'
          user_email: 'shinybrad@pixelandtonic.com'

      - name: Monorepo Split
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          package_directory: 'cms-assets'
          repository_organization: 'craftcms'
          repository_name: 'cms-assets'
          branch: '6.x'
          user_name: 'shinybrad'
          user_email: 'shinybrad@pixelandtonic.com'
